### ISSUE TITLE
Error after running npm run dev.

### ISSUE THREAD

**Issue by Nikhil-blockchain** [tzztson/chatgpt-next.js#1]
I have created the .env file according to the instructions and entered " npm run dev " and this was the error.
<img width="634" alt="Screenshot 2023-04-29 174838" src="https://user-images.githubusercontent.com/113758512/235302448-aa34d948-c816-42b3-a3db-11400d3e7bdf.png">

**Comment by tzztson** [comment]
Please check your node version.
I am using node 16.16.0.
